---
  - name: mysql | Ensure MySQL is installed
    apt: pkg={{ item }} state=installed
    with_items:
      - mysql-server
      - python-mysqldb
    notify: restart mysql

  # remove test databases
  - name: mysql | remove the test database
    mysql_db: name=test state=absent

  # no anonymous users in the database
  - name: mysql | ensure anonymous users are not in the database
    mysql_user: name='' host={{ item }} state=absent
    with_items:
      - localhost
      - "{{ inventory_hostname }}"

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
  - name: mysql | update mysql root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_pass }} priv=*.*:ALL,GRANT
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  - name: mysql | copy MySQL my.cnf config file with root password credentials
    template: src=files/conf/my.cnf.j2 dest=~root/.my.cnf owner=root mode=0600
